# Generated by Django 2.2.15 on 2020-12-23 19:09

from django.db import migrations, models
import private_chat.models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0003_auto_20201223_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='chat_image',
            field=models.ImageField(blank=True, default=private_chat.models.get_default_chat_image, max_length=255, null=True, upload_to=private_chat.models.get_chat_image_filepath),
        ),
    ]
